name: Deploy to VPS

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy files via rsync
        uses: burnett01/rsync-deployments@7.0.2
        with:
          switches: -avz --delete --exclude='.git' --exclude='.github'
          path: ./
          remote_path: /opt/myweb/huy.tanangroup.net/
          remote_host: 14.225.255.139
          remote_port: 22
          remote_user: tester_huy
          remote_key: ${{ secrets.SSH_PRIVATE_KEY }}